services:
  db:
    image: postgis/postgis:16-master
    container_name: artur-db
    environment:
      POSTGRES_USER: ${POSTGIS_USER}
      POSTGRES_PASSWORD: ${POSTGIS_PASSWORD}
      ALLOW_IP_RANGE: ${ALLOW_IP_RANGE}
      POSTGRES_DB: ${POSTGIS_DB}
    ports:
      - "5432:5432"
    volumes:
      # store the data in volumn
      - artur_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGIS_USER} -d ${POSTGIS_DB}"]
    networks:
      - artur_net

  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    image: artur/server
    container_name: artur-server
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      POSTGIS_USER: ${POSTGIS_USER}
      POSTGIS_PASSWORD: ${POSTGIS_PASSWORD}
      POSTGIS_DB: ${POSTGIS_DB}
      DB_HOST: ${DB_HOST}

    command: sh -c "npm start"
    networks:
      - artur_net

  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: artur/dev
    container_name: artur-dev
    depends_on:
      - server
    ports:
      - "5173:5173"
    environment:
      SERVER_HOST: ${SERVER_HOST}

    command: sh -c "npm run dev"
    networks:
      - artur_net

volumes:
  artur_db_data:

networks:
  artur_net:
